# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shodan}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Postmodern"]
  s.date = %q{2010-04-02}
  s.description = %q{A Ruby interface to SHODAN, a computer search engine.}
  s.email = %q{postmodern.mod3@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".specopts",
    ".yardopts",
    "COPYING.txt",
    "ChangeLog.md",
    "README.md",
    "Rakefile",
    "lib/shodan.rb",
    "lib/shodan/countries.rb",
    "lib/shodan/extensions.rb",
    "lib/shodan/extensions/uri.rb",
    "lib/shodan/extensions/uri/http.rb",
    "lib/shodan/extensions/uri/query_params.rb",
    "lib/shodan/has_pages.rb",
    "lib/shodan/host.rb",
    "lib/shodan/page.rb",
    "lib/shodan/query.rb",
    "lib/shodan/shodan.rb",
    "lib/shodan/version.rb",
    "shodan.gemspec",
    "spec/countries_spec.rb",
    "spec/has_pages_examples.rb",
    "spec/host_spec.rb",
    "spec/page_has_hosts_examples.rb",
    "spec/page_spec.rb",
    "spec/query_spec.rb",
    "spec/shodan_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/postmodern/shodan-ruby}
  s.licenses = ["MIT"]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby interface to SHODAN, a computer search engine.}
  s.test_files = [
    "spec/countries_spec.rb",
    "spec/spec_helper.rb",
    "spec/shodan_spec.rb",
    "spec/has_pages_examples.rb",
    "spec/query_spec.rb",
    "spec/page_spec.rb",
    "spec/page_has_hosts_examples.rb",
    "spec/host_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.3"])
    else
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0.5.3"])
  end
end

